---
title: "ipd_plots"
format: html
editor: visual
---

# Iron: forest plot

## Load data

```{r}
pacman::p_load(tidyverse,ggtext)
#load and prepare dataframes
#males
iron_M.all <- readRDS(here::here("data_files","iron_M.all.RDS"))
df_iron_M.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   iron_M.all[15,5],
                                   iron_M.all[16,5],
                                   iron_M.all[17,5],
                                   NA,
                                   iron_M.all[10,5],
                                   iron_M.all[11,5],
                                   NA,
                                   iron_M.all[1,5],
                                   iron_M.all[2,5],
                                   iron_M.all[3,5],
                                   NA,
                                   NA,
                                   iron_M.all[12,5],
                                   iron_M.all[13,5],
                                   NA,
                                   iron_M.all[4,5],
                                   iron_M.all[8,5],
                                   iron_M.all[9,5],
                                   iron_M.all[7,5],
                                   iron_M.all[6,5],
                                   iron_M.all[5,5],
                                   NA,
                                   iron_M.all[18,5],
                                   iron_M.all[19,5],
                                   iron_M.all[20,5],
                                   NA,
                                   iron_M.all[14,5]),
                           effect= c(NA,
                                     iron_M.all[15,1],
                                     iron_M.all[16,1],
                                     iron_M.all[17,1],
                                     NA,
                                     iron_M.all[10,1],
                                     iron_M.all[11,1],
                                     NA,
                                     iron_M.all[1,1],
                                     iron_M.all[2,1],
                                     iron_M.all[3,1],
                                     NA,
                                     NA,
                                     iron_M.all[12,1],
                                     iron_M.all[13,1],
                                     NA,
                                     iron_M.all[4,1],
                                     iron_M.all[8,1],
                                     iron_M.all[9,1],
                                     iron_M.all[7,1],
                                     iron_M.all[6,1],
                                     iron_M.all[5,1],
                                     NA,
                                     iron_M.all[18,1],
                                     iron_M.all[19,1],
                                     iron_M.all[20,1],
                                     NA,
                                     iron_M.all[14,1]),
                             lower=c(NA,
                                     iron_M.all[15,3],
                                     iron_M.all[16,3],
                                     iron_M.all[17,3],
                                     NA,
                                     iron_M.all[10,3],
                                     iron_M.all[11,3],
                                     NA,
                                     iron_M.all[1,3],
                                     iron_M.all[2,3],
                                     iron_M.all[3,3],
                                     NA,
                                     NA,
                                     iron_M.all[12,3],
                                     iron_M.all[13,3],
                                     NA,
                                     iron_M.all[4,3],
                                     iron_M.all[8,3],
                                     iron_M.all[9,3],
                                     iron_M.all[7,3],
                                     iron_M.all[6,3],
                                     iron_M.all[5,3],
                                     NA,
                                     iron_M.all[18,3],
                                     iron_M.all[19,3],
                                     iron_M.all[20,3],
                                     NA,
                                     iron_M.all[14,3]),
                           upper=c(NA,
                                   iron_M.all[15,4],
                                   iron_M.all[16,4],
                                   iron_M.all[17,4],
                                   NA,
                                   iron_M.all[10,4],
                                   iron_M.all[11,4],
                                   NA,
                                   iron_M.all[1,4],
                                   iron_M.all[2,4],
                                   iron_M.all[3,4],
                                   NA,
                                   NA,
                                   iron_M.all[12,4],
                                   iron_M.all[13,4],
                                   NA,
                                   iron_M.all[4,4],
                                   iron_M.all[8,4],
                                   iron_M.all[9,4],
                                   iron_M.all[7,4],
                                   iron_M.all[6,4],
                                   iron_M.all[5,4],
                                   NA,
                                   iron_M.all[18,4],
                                   iron_M.all[19,4],
                                   iron_M.all[20,4],
                                   NA,
                                   iron_M.all[14,4]),
                           p.value=c(NA,
                                     iron_M.all[15,2],
                                     iron_M.all[16,2],
                                     iron_M.all[17,2],
                                     NA,
                                     iron_M.all[10,2],
                                     iron_M.all[11,2],
                                     NA,
                                     iron_M.all[1,2],
                                     iron_M.all[2,2],
                                     iron_M.all[3,2],
                                     NA,
                                     NA,
                                     iron_M.all[12,2],
                                     iron_M.all[13,2],
                                     NA,
                                     iron_M.all[4,2],
                                     iron_M.all[8,2],
                                     iron_M.all[9,2],
                                     iron_M.all[7,2],
                                     iron_M.all[6,2],
                                     iron_M.all[5,2],
                                     NA,
                                     iron_M.all[18,2],
                                     iron_M.all[19,2],
                                     iron_M.all[20,2],
                                     NA,
                                     iron_M.all[14,2]),
                           gender=rep("Males",28))

iron_F.all <- readRDS(here::here("data_files","iron_F.all.RDS"))
df_iron_F.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   iron_F.all[13,5],
                                   iron_F.all[14,5],
                                   iron_F.all[15,5],
                                   NA,
                                   iron_F.all[8,5],
                                   iron_F.all[9,5],
                                   NA,
                                   iron_F.all[1,5],
                                   iron_F.all[2,5],
                                   iron_F.all[3,5],
                                   NA,
                                   NA,
                                   iron_F.all[10,5],
                                   iron_F.all[11,5],
                                   NA,
                                   iron_F.all[4,5],
                                   iron_F.all[6,5],
                                   iron_F.all[7,5],
                                   iron_F.all[5,5],
                                   NA,
                                   NA,
                                   NA,
                                   iron_F.all[16,5],
                                   iron_F.all[17,5],
                                   iron_F.all[18,5],
                                   NA,
                                   iron_F.all[2,5]),
                           effect= c(NA,
                                   iron_F.all[13,1],
                                   iron_F.all[14,1],
                                   iron_F.all[15,1],
                                   NA,
                                   iron_F.all[8,1],
                                   iron_F.all[9,1],
                                   NA,
                                   iron_F.all[1,1],
                                   iron_F.all[2,1],
                                   iron_F.all[3,1],
                                   NA,
                                   NA,
                                   iron_F.all[10,1],
                                   iron_F.all[11,1],
                                   NA,
                                   iron_F.all[4,1],
                                   iron_F.all[6,1],
                                   iron_F.all[7,1],
                                   iron_F.all[5,1],
                                   NA,
                                   NA,
                                   NA,
                                   iron_F.all[16,1],
                                   iron_F.all[17,1],
                                   iron_F.all[18,1],
                                   NA,
                                   iron_F.all[2,1]),
                             lower=c(NA,
                                   iron_F.all[13,3],
                                   iron_F.all[14,3],
                                   iron_F.all[15,3],
                                   NA,
                                   iron_F.all[8,3],
                                   iron_F.all[9,3],
                                   NA,
                                   iron_F.all[1,3],
                                   iron_F.all[2,3],
                                   iron_F.all[3,3],
                                   NA,
                                   NA,
                                   iron_F.all[10,3],
                                   iron_F.all[11,3],
                                   NA,
                                   iron_F.all[4,3],
                                   iron_F.all[6,3],
                                   iron_F.all[7,3],
                                   iron_F.all[5,3],
                                   NA,
                                   NA,
                                   NA,
                                   iron_F.all[16,3],
                                   iron_F.all[17,3],
                                   iron_F.all[18,3],
                                   NA,
                                   iron_F.all[2,3]),
                           upper=c(NA,
                                   iron_F.all[13,4],
                                   iron_F.all[14,4],
                                   iron_F.all[15,4],
                                   NA,
                                   iron_F.all[8,4],
                                   iron_F.all[9,4],
                                   NA,
                                   iron_F.all[1,4],
                                   iron_F.all[2,4],
                                   iron_F.all[3,4],
                                   NA,
                                   NA,
                                   iron_F.all[10,4],
                                   iron_F.all[11,4],
                                   NA,
                                   iron_F.all[4,4],
                                   iron_F.all[6,4],
                                   iron_F.all[7,4],
                                   iron_F.all[5,4],
                                   NA,
                                   NA,
                                   NA,
                                   iron_F.all[16,4],
                                   iron_F.all[17,4],
                                   iron_F.all[18,4],
                                   NA,
                                   iron_F.all[2,4]),
                           p.value=c(NA,
                                   iron_F.all[13,2],
                                   iron_F.all[14,2],
                                   iron_F.all[15,2],
                                   NA,
                                   iron_F.all[8,2],
                                   iron_F.all[9,2],
                                   NA,
                                   iron_F.all[1,2],
                                   iron_F.all[2,2],
                                   iron_F.all[3,2],
                                   NA,
                                   NA,
                                   iron_F.all[10,2],
                                   iron_F.all[11,2],
                                   NA,
                                   iron_F.all[4,2],
                                   iron_F.all[6,2],
                                   iron_F.all[7,2],
                                   iron_F.all[5,2],
                                   NA,
                                   NA,
                                   NA,
                                   iron_F.all[16,2],
                                   iron_F.all[17,2],
                                   iron_F.all[18,2],
                                   NA,
                                   iron_F.all[2,2]),
                           gender=rep("Females",28))

```

## Prepare and format

```{r}
iron_MF.all <- rbind(df_iron_M.f1,df_iron_F.f1) |> 
  mutate(across(c(study,gender),as.factor),
         study=fct_relevel(study,rev(c("Main analysis: Children and Adolescents",
                                       "Children and Adolescents: Model 1",
                                       "Children and Adolescents: Model 2",
                                       "Children and Adolescents: Model 3",
                                       "Subgroup analysis: Children and Adolescents",
                                       "Children",
                                       "Adolescents",
                                       "Main analysis: Adults",
                                       "Adults: Model 1",
                                       "Adults: Model 2",
                                       "Adults: Model 3",
                                       "Subgroup analysis: Adults",
                                       "By age groups",
                                       "Adults",
                                       "Older Adults",
                                       "By comorbidities",
                                       "Anemia",
                                       "Diabetes",
                                       "Hypertension",
                                       "CKD",
                                       "Hemochromatosis",
                                       "Thalassemia",
                                       "By inflammation",
                                       "CRP≥ 3mg/dL",
                                       "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                       "Sensitivity analysis: Adults",
                                       "Model 1"))),
         effect = round(effect,4),
         lower = round(lower,4),
         lower = format(lower,scientific=FALSE),
         lower = as.numeric(lower),
         upper = round(upper,3),
         p.value = ifelse(p.value < 0.001, "<0.001", round(p.value, 3)),
         label=ifelse(!is.na(effect), paste0(format(effect, scientific = FALSE), " (", lower, ", ", upper, "), p=", p.value), NA),
         gender=fct_relevel(gender,c("Males","Females")))

saveRDS(iron_MF.all,file = here::here("data_files","iron_MF.all.RDS"))
```

## Plot

```{r}
#load source theme function
source("~/Docs/myRprojects/theme_personal.function.R")
my.cols<-c("#2166ac",'#ca0020','#404040','#f4a582','#bababa','#ffffff') 

#own graph labels
graph_labels <- rev(c("**Main analysis: Children and Adolescents**",
                  "Children and Adolescents: Model 1",
                  "Children and Adolescents: Model 2",
                  "Children and Adolescents: Model 3",
                  "**Subgroup analysis: Children and Adolescents**",
                  "Children",
                  "Adolescents",
                  "**Main analysis: Adults**",
                  "Adults: Model 1",
                  "Adults: Model 2",
                  "Adults: Model 3",
                  "**Subgroup analysis: Adults**",
                  "***By age groups***",
                  "Adults",
                  "Older Adults",
                  "***By comorbidities***",
                  "Anemia",
                  "Diabetes",
                  "Hypertension",
                  "CKD",
                  "Hemochromatosis",
                  "Thalassemia",
                  "***By inflammation***",
                  "CRP≥ 3mg/dL",
                  "CRP 1-3mg/dL", "CRP<1 mg/dL",
                  "**Sensitivity analysis: Adults**",
                  "Model 1"))

#ggpacket function to combine some layers
#create forest plot
ggpck_for.h<-ggpackets::ggpacket()+
  geom_errorbarh(height=.1,color="#bababa")+
  scale_color_manual(values = my.cols,labels=c("NS","p<0.05"))+
  geom_vline(xintercept=0, color='#404040', linetype='dashed', alpha=.5)+
  theme_personal()+
  geom_hline(yintercept = c(2, 17, 24), linetype = "dashed", color = '#bababa') +
  geom_hline(yintercept = c(21, 28), color = '#404040') +
  scale_y_discrete(labels=graph_labels)+
  #scale_color_discrete(labels=c("NS","p<0.05"))+
  theme(legend.position = "top",
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_markdown()
  )

iron.f1 <- iron_MF.all |>
  ggplot(aes(y = study, x = effect, xmin = lower, xmax = upper)) +
  ggpck_for.h() +
  coord_cartesian(xlim = c(-0.1, 0.3), ylim=c(-2,30), clip = "off") +  # Adjusted x-axis limit
  geom_point(aes(color = p.value < 0.05), size = 3) +
  geom_text(label = iron_MF.all$label, x = 0.175, color = "black") +  # Adjusted x position
  geom_text(label = "Estimate (95% CI), P.Value", x = 0.175, y = 29, color = "#525252",fontface="bold") +
  geom_text(label = "Decreased IMT", x = -0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  geom_text(label = "Increased IMT", x = 0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  labs(title = 'Coefficient plot: Iron and IMT', x = '', y = '') +
  facet_grid(~gender) 

iron.f1> ggsave(filename=here::here("graphs","iron_forest.png"),
                    width=12.5,height=8,dpi=300)
beepr::beep()
```

# Ferritin: forest plot

## Load data

```{r}
#load and prepare dataframes
#males
ferritin_M.all <- readRDS(here::here("data_files","ferritin_M.all.RDS"))
df_ferritin_M.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   ferritin_M.all[15,5],
                                   ferritin_M.all[16,5],
                                   ferritin_M.all[17,5],
                                   NA,
                                   ferritin_M.all[10,5],
                                   ferritin_M.all[11,5],
                                   NA,
                                   ferritin_M.all[1,5],
                                   ferritin_M.all[2,5],
                                   ferritin_M.all[3,5],
                                   NA,
                                   NA,
                                   ferritin_M.all[12,5],
                                   ferritin_M.all[13,5],
                                   NA,
                                   ferritin_M.all[4,5],
                                   ferritin_M.all[8,5],
                                   ferritin_M.all[9,5],
                                   ferritin_M.all[7,5],
                                   ferritin_M.all[6,5],
                                   ferritin_M.all[5,5],
                                   NA,
                                   ferritin_M.all[18,5],
                                   ferritin_M.all[19,5],
                                   ferritin_M.all[20,5],
                                   NA,
                                   ferritin_M.all[14,5]),
                           effect= c(NA,
                                     ferritin_M.all[15,1],
                                     ferritin_M.all[16,1],
                                     ferritin_M.all[17,1],
                                     NA,
                                     ferritin_M.all[10,1],
                                     ferritin_M.all[11,1],
                                     NA,
                                     ferritin_M.all[1,1],
                                     ferritin_M.all[2,1],
                                     ferritin_M.all[3,1],
                                     NA,
                                     NA,
                                     ferritin_M.all[12,1],
                                     ferritin_M.all[13,1],
                                     NA,
                                     ferritin_M.all[4,1],
                                     ferritin_M.all[8,1],
                                     ferritin_M.all[9,1],
                                     ferritin_M.all[7,1],
                                     ferritin_M.all[6,1],
                                     ferritin_M.all[5,1],
                                     NA,
                                     ferritin_M.all[18,1],
                                     ferritin_M.all[19,1],
                                     ferritin_M.all[20,1],
                                     NA,
                                     ferritin_M.all[14,1]),
                           lower=c(NA,
                                   ferritin_M.all[15,3],
                                   ferritin_M.all[16,3],
                                   ferritin_M.all[17,3],
                                   NA,
                                   ferritin_M.all[10,3],
                                   ferritin_M.all[11,3],
                                   NA,
                                   ferritin_M.all[1,3],
                                   ferritin_M.all[2,3],
                                   ferritin_M.all[3,3],
                                   NA,
                                   NA,
                                   ferritin_M.all[12,3],
                                   ferritin_M.all[13,3],
                                   NA,
                                   ferritin_M.all[4,3],
                                   ferritin_M.all[8,3],
                                   ferritin_M.all[9,3],
                                   ferritin_M.all[7,3],
                                   ferritin_M.all[6,3],
                                   ferritin_M.all[5,3],
                                   NA,
                                   ferritin_M.all[18,3],
                                   ferritin_M.all[19,3],
                                   ferritin_M.all[20,3],
                                   NA,
                                   ferritin_M.all[14,3]),
                           upper=c(NA,
                                   ferritin_M.all[15,4],
                                   ferritin_M.all[16,4],
                                   ferritin_M.all[17,4],
                                   NA,
                                   ferritin_M.all[10,4],
                                   ferritin_M.all[11,4],
                                   NA,
                                   ferritin_M.all[1,4],
                                   ferritin_M.all[2,4],
                                   ferritin_M.all[3,4],
                                   NA,
                                   NA,
                                   ferritin_M.all[12,4],
                                   ferritin_M.all[13,4],
                                   NA,
                                   ferritin_M.all[4,4],
                                   ferritin_M.all[8,4],
                                   ferritin_M.all[9,4],
                                   ferritin_M.all[7,4],
                                   ferritin_M.all[6,4],
                                   ferritin_M.all[5,4],
                                   NA,
                                   ferritin_M.all[18,4],
                                   ferritin_M.all[19,4],
                                   ferritin_M.all[20,4],
                                   NA,
                                   ferritin_M.all[14,4]),
                           p.value=c(NA,
                                     ferritin_M.all[15,2],
                                     ferritin_M.all[16,2],
                                     ferritin_M.all[17,2],
                                     NA,
                                     ferritin_M.all[10,2],
                                     ferritin_M.all[11,2],
                                     NA,
                                     ferritin_M.all[1,2],
                                     ferritin_M.all[2,2],
                                     ferritin_M.all[3,2],
                                     NA,
                                     NA,
                                     ferritin_M.all[12,2],
                                     ferritin_M.all[13,2],
                                     NA,
                                     ferritin_M.all[4,2],
                                     ferritin_M.all[8,2],
                                     ferritin_M.all[9,2],
                                     ferritin_M.all[7,2],
                                     ferritin_M.all[6,2],
                                     ferritin_M.all[5,2],
                                     NA,
                                     ferritin_M.all[18,2],
                                     ferritin_M.all[19,2],
                                     ferritin_M.all[20,2],
                                     NA,
                                     ferritin_M.all[14,2]),
                           gender=rep("Males",28))

ferritin_F.all <- readRDS(here::here("data_files","ferritin_F.all.RDS"))
df_ferritin_F.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   ferritin_F.all[13,5],
                                   ferritin_F.all[14,5],
                                   ferritin_F.all[15,5],
                                   NA,
                                   ferritin_F.all[8,5],
                                   ferritin_F.all[9,5],
                                   NA,
                                   ferritin_F.all[1,5],
                                   ferritin_F.all[2,5],
                                   ferritin_F.all[3,5],
                                   NA,
                                   NA,
                                   ferritin_F.all[10,5],
                                   ferritin_F.all[11,5],
                                   NA,
                                   ferritin_F.all[4,5],
                                   ferritin_F.all[6,5],
                                   ferritin_F.all[7,5],
                                   ferritin_F.all[5,5],
                                   NA,
                                   NA,
                                   NA,
                                   ferritin_F.all[16,5],
                                   ferritin_F.all[17,5],
                                   ferritin_F.all[18,5],
                                   NA,
                                   ferritin_F.all[2,5]),
                           effect= c(NA,
                                     ferritin_F.all[13,1],
                                     ferritin_F.all[14,1],
                                     ferritin_F.all[15,1],
                                     NA,
                                     ferritin_F.all[8,1],
                                     ferritin_F.all[9,1],
                                     NA,
                                     ferritin_F.all[1,1],
                                     ferritin_F.all[2,1],
                                     ferritin_F.all[3,1],
                                     NA,
                                     NA,
                                     ferritin_F.all[10,1],
                                     ferritin_F.all[11,1],
                                     NA,
                                     ferritin_F.all[4,1],
                                     ferritin_F.all[6,1],
                                     ferritin_F.all[7,1],
                                     ferritin_F.all[5,1],
                                     NA,
                                     NA,
                                     NA,
                                     ferritin_F.all[16,1],
                                     ferritin_F.all[17,1],
                                     ferritin_F.all[18,1],
                                     NA,
                                     ferritin_F.all[2,1]),
                           lower=c(NA,
                                   ferritin_F.all[13,3],
                                   ferritin_F.all[14,3],
                                   ferritin_F.all[15,3],
                                   NA,
                                   ferritin_F.all[8,3],
                                   ferritin_F.all[9,3],
                                   NA,
                                   ferritin_F.all[1,3],
                                   ferritin_F.all[2,3],
                                   ferritin_F.all[3,3],
                                   NA,
                                   NA,
                                   ferritin_F.all[10,3],
                                   ferritin_F.all[11,3],
                                   NA,
                                   ferritin_F.all[4,3],
                                   ferritin_F.all[6,3],
                                   ferritin_F.all[7,3],
                                   ferritin_F.all[5,3],
                                   NA,
                                   NA,
                                   NA,
                                   ferritin_F.all[16,3],
                                   ferritin_F.all[17,3],
                                   ferritin_F.all[18,3],
                                   NA,
                                   ferritin_F.all[2,3]),
                           upper=c(NA,
                                   ferritin_F.all[13,4],
                                   ferritin_F.all[14,4],
                                   ferritin_F.all[15,4],
                                   NA,
                                   ferritin_F.all[8,4],
                                   ferritin_F.all[9,4],
                                   NA,
                                   ferritin_F.all[1,4],
                                   ferritin_F.all[2,4],
                                   ferritin_F.all[3,4],
                                   NA,
                                   NA,
                                   ferritin_F.all[10,4],
                                   ferritin_F.all[11,4],
                                   NA,
                                   ferritin_F.all[4,4],
                                   ferritin_F.all[6,4],
                                   ferritin_F.all[7,4],
                                   ferritin_F.all[5,4],
                                   NA,
                                   NA,
                                   NA,
                                   ferritin_F.all[16,4],
                                   ferritin_F.all[17,4],
                                   ferritin_F.all[18,4],
                                   NA,
                                   ferritin_F.all[2,4]),
                           p.value=c(NA,
                                     ferritin_F.all[13,2],
                                     ferritin_F.all[14,2],
                                     ferritin_F.all[15,2],
                                     NA,
                                     ferritin_F.all[8,2],
                                     ferritin_F.all[9,2],
                                     NA,
                                     ferritin_F.all[1,2],
                                     ferritin_F.all[2,2],
                                     ferritin_F.all[3,2],
                                     NA,
                                     NA,
                                     ferritin_F.all[10,2],
                                     ferritin_F.all[11,2],
                                     NA,
                                     ferritin_F.all[4,2],
                                     ferritin_F.all[6,2],
                                     ferritin_F.all[7,2],
                                     ferritin_F.all[5,2],
                                     NA,
                                     NA,
                                     NA,
                                     ferritin_F.all[16,2],
                                     ferritin_F.all[17,2],
                                     ferritin_F.all[18,2],
                                     NA,
                                     ferritin_F.all[2,2]),
                           gender=rep("Females",28))
```

## Prepare and format

```{r}
ferritin_MF.all <- rbind(df_ferritin_M.f1,df_ferritin_F.f1) |> 
  mutate(across(c(study,gender),as.factor),
         study=fct_relevel(study,rev(c("Main analysis: Children and Adolescents",
                                       "Children and Adolescents: Model 1",
                                       "Children and Adolescents: Model 2",
                                       "Children and Adolescents: Model 3",
                                       "Subgroup analysis: Children and Adolescents",
                                       "Children",
                                       "Adolescents",
                                       "Main analysis: Adults",
                                       "Adults: Model 1",
                                       "Adults: Model 2",
                                       "Adults: Model 3",
                                       "Subgroup analysis: Adults",
                                       "By age groups",
                                       "Adults",
                                       "Older Adults",
                                       "By comorbidities",
                                       "Anemia",
                                       "Diabetes",
                                       "Hypertension",
                                       "CKD",
                                       "Hemochromatosis",
                                       "Thalassemia",
                                       "By inflammation",
                                       "CRP≥ 3mg/dL",
                                       "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                       "Sensitivity analysis: Adults",
                                       "Model 1"))),
         effect = round(effect,4),
         lower = round(lower,4),
         lower = as.numeric(format(lower,scientific=FALSE)),
         #lower = as.numeric(lower),
         upper = round(upper,3),
         p.value = ifelse(p.value < 0.001, "<0.001", round(p.value, 3)),
         label=ifelse(!is.na(effect), paste0(format(effect, scientific = FALSE), " (", lower, ", ", upper, "), p=", p.value), NA),
         gender=fct_relevel(gender,c("Males","Females")),
         label=str_replace_all(label,"p=<","P<"))

saveRDS(ferritin_MF.all,file = here::here("data_files","ferritin_MF.all.RDS"))
```

## Plot

```{r}
ferritin.f1 <- ferritin_MF.all |>
  ggplot(aes(y = study, x = effect, xmin = lower, xmax = upper)) +
  ggpck_for.h() +
  coord_cartesian(xlim = c(-0.1, 0.3), ylim=c(-2,30), clip = "off") +  # Adjusted x-axis limit
  geom_point(aes(color = p.value < 0.05), size = 3) +
  geom_text(label = ferritin_MF.all$label, x = 0.175, color = "black") +  # Adjusted x position
  geom_text(label = "Estimate (95% CI), P.Value", x = 0.175, y = 29, color = "#525252",fontface="bold") +
  geom_text(label = "Decreased IMT", x = -0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  geom_text(label = "Increased IMT", x = 0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  labs(title = 'Coefficient plot: Ferritin and IMT', x = '', y = '') +
  facet_grid(~gender) 

ferritin.f1> ggsave(filename=here::here("graphs","ferritin_forest.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()
```

# Transferrin: forest plot

## Load data

```{r}
#load and prepare dataframes
#males
transferrin_M.all <- readRDS(here::here("data_files","transferrin_M.all.RDS"))
df_transferrin_M.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   transferrin_M.all[15,5],
                                   transferrin_M.all[16,5],
                                   transferrin_M.all[17,5],
                                   NA,
                                   transferrin_M.all[10,5],
                                   transferrin_M.all[11,5],
                                   NA,
                                   transferrin_M.all[1,5],
                                   transferrin_M.all[2,5],
                                   transferrin_M.all[3,5],
                                   NA,
                                   NA,
                                   transferrin_M.all[12,5],
                                   transferrin_M.all[13,5],
                                   NA,
                                   transferrin_M.all[4,5],
                                   transferrin_M.all[8,5],
                                   transferrin_M.all[9,5],
                                   transferrin_M.all[7,5],
                                   transferrin_M.all[6,5],
                                   transferrin_M.all[5,5],
                                   NA,
                                   transferrin_M.all[18,5],
                                   transferrin_M.all[19,5],
                                   transferrin_M.all[20,5],
                                   NA,
                                   transferrin_M.all[14,5]),
                           effect= c(NA,
                                     transferrin_M.all[15,1],
                                     transferrin_M.all[16,1],
                                     transferrin_M.all[17,1],
                                     NA,
                                     transferrin_M.all[10,1],
                                     transferrin_M.all[11,1],
                                     NA,
                                     transferrin_M.all[1,1],
                                     transferrin_M.all[2,1],
                                     transferrin_M.all[3,1],
                                     NA,
                                     NA,
                                     transferrin_M.all[12,1],
                                     transferrin_M.all[13,1],
                                     NA,
                                     transferrin_M.all[4,1],
                                     transferrin_M.all[8,1],
                                     transferrin_M.all[9,1],
                                     transferrin_M.all[7,1],
                                     transferrin_M.all[6,1],
                                     transferrin_M.all[5,1],
                                     NA,
                                     transferrin_M.all[18,1],
                                     transferrin_M.all[19,1],
                                     transferrin_M.all[20,1],
                                     NA,
                                     transferrin_M.all[14,1]),
                           lower=c(NA,
                                   transferrin_M.all[15,3],
                                   transferrin_M.all[16,3],
                                   transferrin_M.all[17,3],
                                   NA,
                                   transferrin_M.all[10,3],
                                   transferrin_M.all[11,3],
                                   NA,
                                   transferrin_M.all[1,3],
                                   transferrin_M.all[2,3],
                                   transferrin_M.all[3,3],
                                   NA,
                                   NA,
                                   transferrin_M.all[12,3],
                                   transferrin_M.all[13,3],
                                   NA,
                                   transferrin_M.all[4,3],
                                   transferrin_M.all[8,3],
                                   transferrin_M.all[9,3],
                                   transferrin_M.all[7,3],
                                   transferrin_M.all[6,3],
                                   transferrin_M.all[5,3],
                                   NA,
                                   transferrin_M.all[18,3],
                                   transferrin_M.all[19,3],
                                   transferrin_M.all[20,3],
                                   NA,
                                   transferrin_M.all[14,3]),
                           upper=c(NA,
                                   transferrin_M.all[15,4],
                                   transferrin_M.all[16,4],
                                   transferrin_M.all[17,4],
                                   NA,
                                   transferrin_M.all[10,4],
                                   transferrin_M.all[11,4],
                                   NA,
                                   transferrin_M.all[1,4],
                                   transferrin_M.all[2,4],
                                   transferrin_M.all[3,4],
                                   NA,
                                   NA,
                                   transferrin_M.all[12,4],
                                   transferrin_M.all[13,4],
                                   NA,
                                   transferrin_M.all[4,4],
                                   transferrin_M.all[8,4],
                                   transferrin_M.all[9,4],
                                   transferrin_M.all[7,4],
                                   transferrin_M.all[6,4],
                                   transferrin_M.all[5,4],
                                   NA,
                                   transferrin_M.all[18,4],
                                   transferrin_M.all[19,4],
                                   transferrin_M.all[20,4],
                                   NA,
                                   transferrin_M.all[14,4]),
                           p.value=c(NA,
                                     transferrin_M.all[15,2],
                                     transferrin_M.all[16,2],
                                     transferrin_M.all[17,2],
                                     NA,
                                     transferrin_M.all[10,2],
                                     transferrin_M.all[11,2],
                                     NA,
                                     transferrin_M.all[1,2],
                                     transferrin_M.all[2,2],
                                     transferrin_M.all[3,2],
                                     NA,
                                     NA,
                                     transferrin_M.all[12,2],
                                     transferrin_M.all[13,2],
                                     NA,
                                     transferrin_M.all[4,2],
                                     transferrin_M.all[8,2],
                                     transferrin_M.all[9,2],
                                     transferrin_M.all[7,2],
                                     transferrin_M.all[6,2],
                                     transferrin_M.all[5,2],
                                     NA,
                                     transferrin_M.all[18,2],
                                     transferrin_M.all[19,2],
                                     transferrin_M.all[20,2],
                                     NA,
                                     transferrin_M.all[14,2]),
                           gender=rep("Males",28))

transferrin_F.all <- readRDS(here::here("data_files","transferrin_F.all.RDS"))
df_transferrin_F.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   transferrin_F.all[13,5],
                                   transferrin_F.all[14,5],
                                   transferrin_F.all[15,5],
                                   NA,
                                   transferrin_F.all[8,5],
                                   transferrin_F.all[9,5],
                                   NA,
                                   transferrin_F.all[1,5],
                                   transferrin_F.all[2,5],
                                   transferrin_F.all[3,5],
                                   NA,
                                   NA,
                                   transferrin_F.all[10,5],
                                   transferrin_F.all[11,5],
                                   NA,
                                   transferrin_F.all[4,5],
                                   transferrin_F.all[6,5],
                                   transferrin_F.all[7,5],
                                   transferrin_F.all[5,5],
                                   NA,
                                   NA,
                                   NA,
                                   transferrin_F.all[16,5],
                                   transferrin_F.all[17,5],
                                   transferrin_F.all[18,5],
                                   NA,
                                   transferrin_F.all[2,5]),
                           effect= c(NA,
                                     transferrin_F.all[13,1],
                                     transferrin_F.all[14,1],
                                     transferrin_F.all[15,1],
                                     NA,
                                     transferrin_F.all[8,1],
                                     transferrin_F.all[9,1],
                                     NA,
                                     transferrin_F.all[1,1],
                                     transferrin_F.all[2,1],
                                     transferrin_F.all[3,1],
                                     NA,
                                     NA,
                                     transferrin_F.all[10,1],
                                     transferrin_F.all[11,1],
                                     NA,
                                     transferrin_F.all[4,1],
                                     transferrin_F.all[6,1],
                                     transferrin_F.all[7,1],
                                     transferrin_F.all[5,1],
                                     NA,
                                     NA,
                                     NA,
                                     transferrin_F.all[16,1],
                                     transferrin_F.all[17,1],
                                     transferrin_F.all[18,1],
                                     NA,
                                     transferrin_F.all[2,1]),
                           lower=c(NA,
                                   transferrin_F.all[13,3],
                                   transferrin_F.all[14,3],
                                   transferrin_F.all[15,3],
                                   NA,
                                   transferrin_F.all[8,3],
                                   transferrin_F.all[9,3],
                                   NA,
                                   transferrin_F.all[1,3],
                                   transferrin_F.all[2,3],
                                   transferrin_F.all[3,3],
                                   NA,
                                   NA,
                                   transferrin_F.all[10,3],
                                   transferrin_F.all[11,3],
                                   NA,
                                   transferrin_F.all[4,3],
                                   transferrin_F.all[6,3],
                                   transferrin_F.all[7,3],
                                   transferrin_F.all[5,3],
                                   NA,
                                   NA,
                                   NA,
                                   transferrin_F.all[16,3],
                                   transferrin_F.all[17,3],
                                   transferrin_F.all[18,3],
                                   NA,
                                   transferrin_F.all[2,3]),
                           upper=c(NA,
                                   transferrin_F.all[13,4],
                                   transferrin_F.all[14,4],
                                   transferrin_F.all[15,4],
                                   NA,
                                   transferrin_F.all[8,4],
                                   transferrin_F.all[9,4],
                                   NA,
                                   transferrin_F.all[1,4],
                                   transferrin_F.all[2,4],
                                   transferrin_F.all[3,4],
                                   NA,
                                   NA,
                                   transferrin_F.all[10,4],
                                   transferrin_F.all[11,4],
                                   NA,
                                   transferrin_F.all[4,4],
                                   transferrin_F.all[6,4],
                                   transferrin_F.all[7,4],
                                   transferrin_F.all[5,4],
                                   NA,
                                   NA,
                                   NA,
                                   transferrin_F.all[16,4],
                                   transferrin_F.all[17,4],
                                   transferrin_F.all[18,4],
                                   NA,
                                   transferrin_F.all[2,4]),
                           p.value=c(NA,
                                     transferrin_F.all[13,2],
                                     transferrin_F.all[14,2],
                                     transferrin_F.all[15,2],
                                     NA,
                                     transferrin_F.all[8,2],
                                     transferrin_F.all[9,2],
                                     NA,
                                     transferrin_F.all[1,2],
                                     transferrin_F.all[2,2],
                                     transferrin_F.all[3,2],
                                     NA,
                                     NA,
                                     transferrin_F.all[10,2],
                                     transferrin_F.all[11,2],
                                     NA,
                                     transferrin_F.all[4,2],
                                     transferrin_F.all[6,2],
                                     transferrin_F.all[7,2],
                                     transferrin_F.all[5,2],
                                     NA,
                                     NA,
                                     NA,
                                     transferrin_F.all[16,2],
                                     transferrin_F.all[17,2],
                                     transferrin_F.all[18,2],
                                     NA,
                                     transferrin_F.all[2,2]),
                           gender=rep("Females",28))
```

## Prepare and format

```{r}
transferrin_MF.all <- rbind(df_transferrin_M.f1,df_transferrin_F.f1) |> 
  mutate(across(c(study,gender),as.factor),
         study=fct_relevel(study,rev(c("Main analysis: Children and Adolescents",
                                       "Children and Adolescents: Model 1",
                                       "Children and Adolescents: Model 2",
                                       "Children and Adolescents: Model 3",
                                       "Subgroup analysis: Children and Adolescents",
                                       "Children",
                                       "Adolescents",
                                       "Main analysis: Adults",
                                       "Adults: Model 1",
                                       "Adults: Model 2",
                                       "Adults: Model 3",
                                       "Subgroup analysis: Adults",
                                       "By age groups",
                                       "Adults",
                                       "Older Adults",
                                       "By comorbidities",
                                       "Anemia",
                                       "Diabetes",
                                       "Hypertension",
                                       "CKD",
                                       "Hemochromatosis",
                                       "Thalassemia",
                                       "By inflammation",
                                       "CRP≥ 3mg/dL",
                                       "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                       "Sensitivity analysis: Adults",
                                       "Model 1"))),
         effect = round(effect,4),
         lower = round(lower,4),
         lower = format(lower,scientific=FALSE),
         lower = as.numeric(lower),
         upper = round(upper,3),
         p.value = ifelse(p.value < 0.001, "<0.001", round(p.value, 3)),
         label=ifelse(!is.na(effect), paste0(format(effect, scientific = FALSE), " (", lower, ", ", upper, "), p=", p.value), NA),
         gender=fct_relevel(gender,c("Males","Females")),
         label=str_replace_all(label,"p=<","P<"))

saveRDS(transferrin_MF.all,file = here::here("data_files","transferrin_MF.all.RDS"))
```

## Plot

```{r}
transferrin.f1 <- transferrin_MF.all |>
  ggplot(aes(y = study, x = effect, xmin = lower, xmax = upper)) +
  ggpck_for.h() +
  coord_cartesian(xlim = c(-0.1, 0.3), ylim=c(-2,30), clip = "off") +  # Adjusted x-axis limit
  geom_point(aes(color = p.value < 0.05), size = 3) +
  geom_text(label = transferrin_MF.all$label, x = 0.175, color = "black") +  # Adjusted x position
  geom_text(label = "Estimate (95% CI), P.Value", x = 0.175, y = 29, color = "#525252",fontface="bold") +
  geom_text(label = "Decreased IMT", x = -0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  geom_text(label = "Increased IMT", x = 0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  labs(title = 'Coefficient plot: Transferrin and IMT', x = '', y = '') +
  facet_grid(~gender) 


transferrin.f1> ggsave(filename=here::here("graphs","transferrin_forest.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()
```

# TSAT: forest plot

## Load data

```{r}
#load and prepare dataframes
#males
tfsat_M.all <- readRDS(here::here("data_files","tfsat_M.all.RDS"))
df_tfsat_M.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   tfsat_M.all[15,5],
                                   tfsat_M.all[16,5],
                                   tfsat_M.all[17,5],
                                   NA,
                                   tfsat_M.all[10,5],
                                   tfsat_M.all[11,5],
                                   NA,
                                   tfsat_M.all[1,5],
                                   tfsat_M.all[2,5],
                                   tfsat_M.all[3,5],
                                   NA,
                                   NA,
                                   tfsat_M.all[12,5],
                                   tfsat_M.all[13,5],
                                   NA,
                                   tfsat_M.all[4,5],
                                   tfsat_M.all[8,5],
                                   tfsat_M.all[9,5],
                                   tfsat_M.all[7,5],
                                   tfsat_M.all[6,5],
                                   tfsat_M.all[5,5],
                                   NA,
                                   tfsat_M.all[18,5],
                                   tfsat_M.all[19,5],
                                   tfsat_M.all[20,5],
                                   NA,
                                   tfsat_M.all[14,5]),
                           effect= c(NA,
                                     tfsat_M.all[15,1],
                                     tfsat_M.all[16,1],
                                     tfsat_M.all[17,1],
                                     NA,
                                     tfsat_M.all[10,1],
                                     tfsat_M.all[11,1],
                                     NA,
                                     tfsat_M.all[1,1],
                                     tfsat_M.all[2,1],
                                     tfsat_M.all[3,1],
                                     NA,
                                     NA,
                                     tfsat_M.all[12,1],
                                     tfsat_M.all[13,1],
                                     NA,
                                     tfsat_M.all[4,1],
                                     tfsat_M.all[8,1],
                                     tfsat_M.all[9,1],
                                     tfsat_M.all[7,1],
                                     tfsat_M.all[6,1],
                                     tfsat_M.all[5,1],
                                     NA,
                                     tfsat_M.all[18,1],
                                     tfsat_M.all[19,1],
                                     tfsat_M.all[20,1],
                                     NA,
                                     tfsat_M.all[14,1]),
                           lower=c(NA,
                                   tfsat_M.all[15,3],
                                   tfsat_M.all[16,3],
                                   tfsat_M.all[17,3],
                                   NA,
                                   tfsat_M.all[10,3],
                                   tfsat_M.all[11,3],
                                   NA,
                                   tfsat_M.all[1,3],
                                   tfsat_M.all[2,3],
                                   tfsat_M.all[3,3],
                                   NA,
                                   NA,
                                   tfsat_M.all[12,3],
                                   tfsat_M.all[13,3],
                                   NA,
                                   tfsat_M.all[4,3],
                                   tfsat_M.all[8,3],
                                   tfsat_M.all[9,3],
                                   tfsat_M.all[7,3],
                                   tfsat_M.all[6,3],
                                   tfsat_M.all[5,3],
                                   NA,
                                   tfsat_M.all[18,3],
                                   tfsat_M.all[19,3],
                                   tfsat_M.all[20,3],
                                   NA,
                                   tfsat_M.all[14,3]),
                           upper=c(NA,
                                   tfsat_M.all[15,4],
                                   tfsat_M.all[16,4],
                                   tfsat_M.all[17,4],
                                   NA,
                                   tfsat_M.all[10,4],
                                   tfsat_M.all[11,4],
                                   NA,
                                   tfsat_M.all[1,4],
                                   tfsat_M.all[2,4],
                                   tfsat_M.all[3,4],
                                   NA,
                                   NA,
                                   tfsat_M.all[12,4],
                                   tfsat_M.all[13,4],
                                   NA,
                                   tfsat_M.all[4,4],
                                   tfsat_M.all[8,4],
                                   tfsat_M.all[9,4],
                                   tfsat_M.all[7,4],
                                   tfsat_M.all[6,4],
                                   tfsat_M.all[5,4],
                                   NA,
                                   tfsat_M.all[18,4],
                                   tfsat_M.all[19,4],
                                   tfsat_M.all[20,4],
                                   NA,
                                   tfsat_M.all[14,4]),
                           p.value=c(NA,
                                     tfsat_M.all[15,2],
                                     tfsat_M.all[16,2],
                                     tfsat_M.all[17,2],
                                     NA,
                                     tfsat_M.all[10,2],
                                     tfsat_M.all[11,2],
                                     NA,
                                     tfsat_M.all[1,2],
                                     tfsat_M.all[2,2],
                                     tfsat_M.all[3,2],
                                     NA,
                                     NA,
                                     tfsat_M.all[12,2],
                                     tfsat_M.all[13,2],
                                     NA,
                                     tfsat_M.all[4,2],
                                     tfsat_M.all[8,2],
                                     tfsat_M.all[9,2],
                                     tfsat_M.all[7,2],
                                     tfsat_M.all[6,2],
                                     tfsat_M.all[5,2],
                                     NA,
                                     tfsat_M.all[18,2],
                                     tfsat_M.all[19,2],
                                     tfsat_M.all[20,2],
                                     NA,
                                     tfsat_M.all[14,2]),
                           gender=rep("Males",28))

tfsat_F.all <- readRDS(here::here("data_files","tfsat_F.all.RDS"))
df_tfsat_F.f1 <- data.frame(study=c("Main analysis: Children and Adolescents",
                                   "Children and Adolescents: Model 1",
                                   "Children and Adolescents: Model 2",
                                   "Children and Adolescents: Model 3",
                                   "Subgroup analysis: Children and Adolescents",
                                   "Children",
                                   "Adolescents",
                                   "Main analysis: Adults",
                                   "Adults: Model 1",
                                   "Adults: Model 2",
                                   "Adults: Model 3",
                                   "Subgroup analysis: Adults",
                                   "By age groups",
                                   "Adults",
                                   "Older Adults",
                                   "By comorbidities",
                                   "Anemia",
                                   "Diabetes",
                                   "Hypertension",
                                   "CKD",
                                   "Hemochromatosis",
                                   "Thalassemia",
                                   "By inflammation",
                                   "CRP≥ 3mg/dL",
                                   "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                   "Sensitivity analysis: Adults",
                                   "Model 1"),
                           index=1:28,
                           model=c(NA,
                                   tfsat_F.all[13,5],
                                   tfsat_F.all[14,5],
                                   tfsat_F.all[15,5],
                                   NA,
                                   tfsat_F.all[8,5],
                                   tfsat_F.all[9,5],
                                   NA,
                                   tfsat_F.all[1,5],
                                   tfsat_F.all[2,5],
                                   tfsat_F.all[3,5],
                                   NA,
                                   NA,
                                   tfsat_F.all[10,5],
                                   tfsat_F.all[11,5],
                                   NA,
                                   tfsat_F.all[4,5],
                                   tfsat_F.all[6,5],
                                   tfsat_F.all[7,5],
                                   tfsat_F.all[5,5],
                                   NA,
                                   NA,
                                   NA,
                                   tfsat_F.all[16,5],
                                   tfsat_F.all[17,5],
                                   tfsat_F.all[18,5],
                                   NA,
                                   tfsat_F.all[2,5]),
                           effect= c(NA,
                                     tfsat_F.all[13,1],
                                     tfsat_F.all[14,1],
                                     tfsat_F.all[15,1],
                                     NA,
                                     tfsat_F.all[8,1],
                                     tfsat_F.all[9,1],
                                     NA,
                                     tfsat_F.all[1,1],
                                     tfsat_F.all[2,1],
                                     tfsat_F.all[3,1],
                                     NA,
                                     NA,
                                     tfsat_F.all[10,1],
                                     tfsat_F.all[11,1],
                                     NA,
                                     tfsat_F.all[4,1],
                                     tfsat_F.all[6,1],
                                     tfsat_F.all[7,1],
                                     tfsat_F.all[5,1],
                                     NA,
                                     NA,
                                     NA,
                                     tfsat_F.all[16,1],
                                     tfsat_F.all[17,1],
                                     tfsat_F.all[18,1],
                                     NA,
                                     tfsat_F.all[2,1]),
                           lower=c(NA,
                                   tfsat_F.all[13,3],
                                   tfsat_F.all[14,3],
                                   tfsat_F.all[15,3],
                                   NA,
                                   tfsat_F.all[8,3],
                                   tfsat_F.all[9,3],
                                   NA,
                                   tfsat_F.all[1,3],
                                   tfsat_F.all[2,3],
                                   tfsat_F.all[3,3],
                                   NA,
                                   NA,
                                   tfsat_F.all[10,3],
                                   tfsat_F.all[11,3],
                                   NA,
                                   tfsat_F.all[4,3],
                                   tfsat_F.all[6,3],
                                   tfsat_F.all[7,3],
                                   tfsat_F.all[5,3],
                                   NA,
                                   NA,
                                   NA,
                                   tfsat_F.all[16,3],
                                   tfsat_F.all[17,3],
                                   tfsat_F.all[18,3],
                                   NA,
                                   tfsat_F.all[2,3]),
                           upper=c(NA,
                                   tfsat_F.all[13,4],
                                   tfsat_F.all[14,4],
                                   tfsat_F.all[15,4],
                                   NA,
                                   tfsat_F.all[8,4],
                                   tfsat_F.all[9,4],
                                   NA,
                                   tfsat_F.all[1,4],
                                   tfsat_F.all[2,4],
                                   tfsat_F.all[3,4],
                                   NA,
                                   NA,
                                   tfsat_F.all[10,4],
                                   tfsat_F.all[11,4],
                                   NA,
                                   tfsat_F.all[4,4],
                                   tfsat_F.all[6,4],
                                   tfsat_F.all[7,4],
                                   tfsat_F.all[5,4],
                                   NA,
                                   NA,
                                   NA,
                                   tfsat_F.all[16,4],
                                   tfsat_F.all[17,4],
                                   tfsat_F.all[18,4],
                                   NA,
                                   tfsat_F.all[2,4]),
                           p.value=c(NA,
                                     tfsat_F.all[13,2],
                                     tfsat_F.all[14,2],
                                     tfsat_F.all[15,2],
                                     NA,
                                     tfsat_F.all[8,2],
                                     tfsat_F.all[9,2],
                                     NA,
                                     tfsat_F.all[1,2],
                                     tfsat_F.all[2,2],
                                     tfsat_F.all[3,2],
                                     NA,
                                     NA,
                                     tfsat_F.all[10,2],
                                     tfsat_F.all[11,2],
                                     NA,
                                     tfsat_F.all[4,2],
                                     tfsat_F.all[6,2],
                                     tfsat_F.all[7,2],
                                     tfsat_F.all[5,2],
                                     NA,
                                     NA,
                                     NA,
                                     tfsat_F.all[16,2],
                                     tfsat_F.all[17,2],
                                     tfsat_F.all[18,2],
                                     NA,
                                     tfsat_F.all[2,2]),
                           gender=rep("Females",28))

```

## Prepare and format

```{r}
tfsat_MF.all <- rbind(df_tfsat_M.f1,df_tfsat_F.f1) |> 
  mutate(across(c(study,gender),as.factor),
         study=fct_relevel(study,rev(c("Main analysis: Children and Adolescents",
                                       "Children and Adolescents: Model 1",
                                       "Children and Adolescents: Model 2",
                                       "Children and Adolescents: Model 3",
                                       "Subgroup analysis: Children and Adolescents",
                                       "Children",
                                       "Adolescents",
                                       "Main analysis: Adults",
                                       "Adults: Model 1",
                                       "Adults: Model 2",
                                       "Adults: Model 3",
                                       "Subgroup analysis: Adults",
                                       "By age groups",
                                       "Adults",
                                       "Older Adults",
                                       "By comorbidities",
                                       "Anemia",
                                       "Diabetes",
                                       "Hypertension",
                                       "CKD",
                                       "Hemochromatosis",
                                       "Thalassemia",
                                       "By inflammation",
                                       "CRP≥ 3mg/dL",
                                       "CRP 1-3mg/dL", "CRP<1 mg/dL",
                                       "Sensitivity analysis: Adults",
                                       "Model 1"))),
         effect = round(effect,4),
         lower = round(lower,4),
         lower = format(lower,scientific=FALSE),
         lower = as.numeric(lower),
         upper = round(upper,3),
         p.value = ifelse(p.value < 0.001, "<0.001", round(p.value, 3)),
         label=ifelse(!is.na(effect), paste0(format(effect, scientific = FALSE), " (", lower, ", ", upper, "), p=", p.value), NA),
         gender=fct_relevel(gender,c("Males","Females")),
         label=str_replace_all(label,"p=<","P<"))


saveRDS(tfsat_MF.all,file = here::here("data_files","tfsat_MF.all.RDS"))
```

## Plot

```{r}
tfsat.f1 <- tfsat_MF.all |>
  ggplot(aes(y = study, x = effect, xmin = lower, xmax = upper)) +
  ggpck_for.h() +
  coord_cartesian(xlim = c(-0.1, 0.3), ylim=c(-2,30), clip = "off") +  # Adjusted x-axis limit
  geom_point(aes(color = p.value < 0.05), size = 3) +
  geom_text(label = tfsat_MF.all$label, x = 0.175, color = "black") +  # Adjusted x position
  geom_text(label = "Estimate (95% CI), P.Value", x = 0.175, y = 29, color = "#525252",fontface="bold") +
  geom_text(label = "Decreased IMT", x = -0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  geom_text(label = "Increased IMT", x = 0.06, y = -1.5, color = "#525252") +  # Adjusted x position
  labs(title = 'Coefficient plot: TSAT and IMT', x = '', y = '') +
  facet_grid(~gender) 

tfsat.f1> ggsave(filename=here::here("graphs","tfsat_forest.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()
```

# Iron density plot

```{r}
pacman::p_load(ggpubr,ggdist,gghalves,tidyverse)
my.cols<-c("#195e83","#ca0020","#69bdd2","#ebb678","#80391e","#e07b39","#cce7e8")

data_frame1 <- readRDS(file=here::here("data_files","data_frame1.RDS"))|>
  mutate(gender=fct_recode(gender,Males="0",Females="1"))

iron.d1 <- data_frame1 |> 
  filter(!is.na(age_gp)) |> 
  ggplot(aes(x = gender, y = iron, color = gender)) +
  ggdist::stat_halfeye(aes(fill = gender),
                       adjust = 0.5, width = 0.6,
                       .width = 0, alpha=0.4,
                       justification = -0.2,
                       point_colour = NA) +
  geom_boxplot(aes(color = gender,fill = gender),
               alpha=0.4,width = 0.15, outlier.shape = NA) +
  gghalves::geom_half_point(aes(color = gender),
                            side = "l", range_scale = 0.4, alpha = 0.15) +
  theme_pubr() +
  facet_grid(~age_gp)+
  stat_compare_means(label.y = 45) +
  scale_color_manual(values = my.cols) +
  scale_fill_manual(values = my.cols) +
  labs(x="",y="Iron (µg/dL)",title="Serum Iron")+
  theme(legend.position = "none")

iron.d1> ggsave(filename=here::here("graphs","iron_density.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()

```

# Ferritin density plot

```{r}

ferritin.d1 <- data_frame1 |> 
  filter(!is.na(age_gp)) |> 
  ggplot(aes(x = gender, y = ferritin, color = gender)) +
  ggdist::stat_halfeye(aes(fill = gender),
                       adjust = 0.5, width = 0.6,
                       .width = 0, alpha=0.4,
                       justification = -0.2,
                       point_colour = NA) +
  geom_boxplot(aes(color = gender,fill = gender),
               alpha=0.4,width = 0.15, outlier.shape = NA) +
  gghalves::geom_half_point(aes(color = gender),
                            side = "l", range_scale = 0.4, alpha = 0.15) +
  theme_pubr() +
  facet_grid(~age_gp)+
  stat_compare_means() +
  scale_color_manual(values = my.cols) +
  scale_fill_manual(values = my.cols) +
  scale_y_log10()+
  labs(x="",y="Ferritin (µg/dL)",title="Serum Ferritin")+
  theme(legend.position = "none")

ferritin.d1> ggsave(filename=here::here("graphs","ferritin_density.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()
```

# Transferrin density plot

```{r}

transferrin.d1 <- data_frame1 |> 
  filter(!is.na(age_gp)) |> 
  ggplot(aes(x = gender, y = transferrin, color = gender)) +
  ggdist::stat_halfeye(aes(fill = gender),
                       adjust = 0.5, width = 0.6,
                       .width = 0, alpha=0.4,
                       justification = -0.2,
                       point_colour = NA) +
  geom_boxplot(aes(color = gender,fill = gender),
               alpha=0.4,width = 0.15, outlier.shape = NA) +
  gghalves::geom_half_point(aes(color = gender),
                            side = "l", range_scale = 0.4, alpha = 0.15) +
  theme_pubr() +
  facet_grid(~age_gp)+
  stat_compare_means() +
  scale_color_manual(values = my.cols) +
  scale_fill_manual(values = my.cols) +
  labs(x="",y="Transferrin (mg/dL)",title="Serum Transferrin")+
  theme(legend.position = "none")

transferrin.d1> ggsave(filename=here::here("graphs","transferrin_density.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()
```

# TSAT density plot

```{r}

tfsat.d1 <- data_frame1 |> 
  filter(!is.na(age_gp)) |> 
  ggplot(aes(x = gender, y = tfsat, color = gender)) +
  ggdist::stat_halfeye(aes(fill = gender),
                       adjust = 0.5, width = 0.6,
                       .width = 0, alpha=0.4,
                       justification = -0.2,
                       point_colour = NA) +
  geom_boxplot(aes(color = gender,fill = gender),
               alpha=0.4,width = 0.15, outlier.shape = NA) +
  gghalves::geom_half_point(aes(color = gender),
                            side = "l", range_scale = 0.4, alpha = 0.15) +
  theme_pubr() +
  facet_grid(~age_gp)+
  stat_compare_means() +
  scale_color_manual(values = my.cols) +
  scale_fill_manual(values = my.cols) +
  labs(x="",y="TSAT (%)",title="Serum TSAT")+
  theme(legend.position = "none")

tfsat.d1> ggsave(filename=here::here("graphs","tfsat_density.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()
```

# IMT density plot

# LOA analysis plot

## Males

```{r}
ferritin_LOA_M <- readRDS(file=here::here("data_files","ferritin_LOA_M.rds"))
#Make dataframe
df_ferritin_LOA_m <- data.frame(study=c("Adult Males: Model 3",
                                   "Leave One Out Analysis",
                                   "Diabetes = Yes",
                                   "Hypertension = Yes",
                                   "CKD = Yes",
                                   "Smokers",
                                   "CRP>1 mg/dL",
                                   "CRP>3 mg/dL",
                                   "BMI>25",
                                   "Adults (18-65 years)",
                                   "Older Adults (>=65 years)",
                                   "LDL >100 mg/dL",
                                   "HDL <40 mg/dL",
                                   "TAG >150 mg/dL"),
                           index=1:14,
                           effect=c(ferritin_LOA_M[13,1],
                                    NA,
                                    ferritin_LOA_M[1,1],
                                    ferritin_LOA_M[2,1],
                                    ferritin_LOA_M[3,1],
                                    ferritin_LOA_M[4,1],
                                    ferritin_LOA_M[5,1],
                                    ferritin_LOA_M[6,1],
                                    ferritin_LOA_M[7,1],
                                    ferritin_LOA_M[8,1],
                                    ferritin_LOA_M[9,1],
                                    ferritin_LOA_M[10,1],
                                    ferritin_LOA_M[11,1],
                                    ferritin_LOA_M[12,1]
                                    ),
                           lower=c(ferritin_LOA_M[13,3],
                                   NA,
                                   ferritin_LOA_M[1,3],
                                   ferritin_LOA_M[2,3],
                                   ferritin_LOA_M[3,3],
                                   ferritin_LOA_M[4,3],
                                   ferritin_LOA_M[5,3],
                                   ferritin_LOA_M[6,3],
                                   ferritin_LOA_M[7,3],
                                   ferritin_LOA_M[8,3],
                                   ferritin_LOA_M[9,3],
                                   ferritin_LOA_M[10,3],
                                   ferritin_LOA_M[11,3],
                                   ferritin_LOA_M[12,3]
                           ),
                           upper=c(ferritin_LOA_M[13,4],
                                   NA,
                                   ferritin_LOA_M[1,4],
                                   ferritin_LOA_M[2,4],
                                   ferritin_LOA_M[3,4],
                                   ferritin_LOA_M[4,4],
                                   ferritin_LOA_M[5,4],
                                   ferritin_LOA_M[6,4],
                                   ferritin_LOA_M[7,4],
                                   ferritin_LOA_M[8,4],
                                   ferritin_LOA_M[9,4],
                                   ferritin_LOA_M[10,4],
                                   ferritin_LOA_M[11,4],
                                   ferritin_LOA_M[12,4]
                           ),
                           p.value=c(ferritin_LOA_M[13,2],
                                     NA,
                                     ferritin_LOA_M[1,2],
                                     ferritin_LOA_M[2,2],
                                     ferritin_LOA_M[3,2],
                                     ferritin_LOA_M[4,2],
                                     ferritin_LOA_M[5,2],
                                     ferritin_LOA_M[6,2],
                                     ferritin_LOA_M[7,2],
                                     ferritin_LOA_M[8,2],
                                     ferritin_LOA_M[9,2],
                                     ferritin_LOA_M[10,2],
                                     ferritin_LOA_M[11,2],
                                     ferritin_LOA_M[12,2]
                           ),
                           label=c(ferritin_LOA_M[13,7],
                                   NA,
                                   ferritin_LOA_M[1,7],
                                   ferritin_LOA_M[2,7],
                                   ferritin_LOA_M[3,7],
                                   ferritin_LOA_M[4,7],
                                   ferritin_LOA_M[5,7],
                                   ferritin_LOA_M[6,7],
                                   ferritin_LOA_M[7,7],
                                   ferritin_LOA_M[8,7],
                                   ferritin_LOA_M[9,7],
                                   ferritin_LOA_M[10,7],
                                   ferritin_LOA_M[11,7],
                                   ferritin_LOA_M[12,7]
                           )) |> 
  mutate(lower=as.numeric(lower),
         study=fct_relevel(study,rev(c("Adult Males: Model 3",
                                             "Leave One Out Analysis",
                                             "Diabetes = Yes",
                                             "Hypertension = Yes",
                                             "CKD = Yes",
                                             "Smokers",
                                             "CRP>1 mg/dL",
                                             "CRP>3 mg/dL",
                                             "BMI>25",
                                             "Adults (18-65 years)",
                                             "Older Adults (>=65 years)",
                                             "LDL >100 mg/dL",
                                             "HDL <40 mg/dL",
                                             "TAG >150 mg/dL"))))

loa_labels <- rev(c("**Adult Males: Model 3**",
                    "***Leave One Out Analysis***",
                    "Diabetes = Yes",
                    "Hypertension = Yes",
                    "CKD = Yes",
                    "Smokers",
                    "CRP>1 mg/dL",
                    "CRP>3 mg/dL",
                    "BMI>25",
                    "Adults (18-65 years)",
                    "Older Adults (>=65 years)",
                    "LDL >100 mg/dL",
                    "HDL <40 mg/dL",
                    "TAG >150 mg/dL"))

#plot
#create forest plot
ggpck_for.h1<-ggpackets::ggpacket()+
  geom_errorbarh(height=.1,color="#bababa")+
  scale_color_manual(values = my.cols)+
  geom_vline(xintercept=0, color='#404040', linetype='dashed', alpha=.5)+
  theme_personal()+
  geom_hline(yintercept = 13, linetype = "dashed", color = '#bababa') +
  scale_y_discrete(labels=loa_labels)+
  theme(legend.position = "none",
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_markdown()
  )

ferritin_LOA_M.f1 <- df_ferritin_LOA_m |>
  ggplot(aes(y = study, x = effect, xmin = lower, xmax = upper)) +
  ggpck_for.h1() +
  coord_cartesian(xlim = c(-0.05, 0.1), ylim=c(-2,15), clip = "off") +  # Adjusted x-axis limit
  geom_point(aes(color = p.value < 0.05), size = 3) +
  geom_text(label = df_ferritin_LOA_m$label, x = 0.075, color = "black") +  # Adjusted x position
  geom_text(label = "Estimate (95% CI), P.Value", x = 0.075, y = 14.75, color = "#525252",fontface="bold") +
  geom_text(label = "Decreased IMT", x = -0.03, y = -1.5, color = "#525252") +  # Adjusted x position
  geom_text(label = "Increased IMT", x = 0.03, y = -1.5, color = "#525252") +  # Adjusted x position
  labs(title = 'Leave One Out Analysis: Ferritin and IMT (Males)', x = '', y = '') 

ferritin_LOA_M.f1 |> ggsave(filename=here::here("graphs","ferritin_LOA_M.png"),
                width=12.5,height=8,dpi=300)
beepr::beep()
```

## Females

```{r}
#loa plot females
ferritin_LOA_F <- readRDS(file=here::here("data_files","ferritin_LOA_F.rds"))
#Make dataframe
df_ferritin_LOA_F <- data.frame(study=c("Adult Females: Model 2",
                                        "Leave One Out Analysis",
                                        "Diabetes = Yes",
                                        "Hypertension = Yes",
                                        "CKD = Yes",
                                        "Smokers",
                                        "CRP>1 mg/dL",
                                        "CRP>3 mg/dL",
                                        "BMI>25",
                                        "Adults (18-65 years)",
                                        "Older Adults (>=65 years)",
                                        "LDL >100 mg/dL",
                                        "HDL <50 mg/dL",
                                        "TAG >150 mg/dL"),
                                index=1:14,
                                effect=c(ferritin_LOA_F[13,1],
                                         NA,
                                         ferritin_LOA_F[1,1],
                                         ferritin_LOA_F[2,1],
                                         ferritin_LOA_F[3,1],
                                         ferritin_LOA_F[4,1],
                                         ferritin_LOA_F[5,1],
                                         ferritin_LOA_F[6,1],
                                         ferritin_LOA_F[7,1],
                                         ferritin_LOA_F[8,1],
                                         ferritin_LOA_F[9,1],
                                         ferritin_LOA_F[10,1],
                                         ferritin_LOA_F[11,1],
                                         ferritin_LOA_F[12,1]
                                ),
                                lower=c(ferritin_LOA_F[13,3],
                                        NA,
                                        ferritin_LOA_F[1,3],
                                        ferritin_LOA_F[2,3],
                                        ferritin_LOA_F[3,3],
                                        ferritin_LOA_F[4,3],
                                        ferritin_LOA_F[5,3],
                                        ferritin_LOA_F[6,3],
                                        ferritin_LOA_F[7,3],
                                        ferritin_LOA_F[8,3],
                                        ferritin_LOA_F[9,3],
                                        ferritin_LOA_F[10,3],
                                        ferritin_LOA_F[11,3],
                                        ferritin_LOA_F[12,3]
                                ),
                                upper=c(ferritin_LOA_F[13,4],
                                        NA,
                                        ferritin_LOA_F[1,4],
                                        ferritin_LOA_F[2,4],
                                        ferritin_LOA_F[3,4],
                                        ferritin_LOA_F[4,4],
                                        ferritin_LOA_F[5,4],
                                        ferritin_LOA_F[6,4],
                                        ferritin_LOA_F[7,4],
                                        ferritin_LOA_F[8,4],
                                        ferritin_LOA_F[9,4],
                                        ferritin_LOA_F[10,4],
                                        ferritin_LOA_F[11,4],
                                        ferritin_LOA_F[12,4]
                                ),
                                p.value=c(ferritin_LOA_F[13,2],
                                          NA,
                                          ferritin_LOA_F[1,2],
                                          ferritin_LOA_F[2,2],
                                          ferritin_LOA_F[3,2],
                                          ferritin_LOA_F[4,2],
                                          ferritin_LOA_F[5,2],
                                          ferritin_LOA_F[6,2],
                                          ferritin_LOA_F[7,2],
                                          ferritin_LOA_F[8,2],
                                          ferritin_LOA_F[9,2],
                                          ferritin_LOA_F[10,2],
                                          ferritin_LOA_F[11,2],
                                          ferritin_LOA_F[12,2]
                                ),
                                label=c(ferritin_LOA_F[13,7],
                                        NA,
                                        ferritin_LOA_F[1,7],
                                        ferritin_LOA_F[2,7],
                                        ferritin_LOA_F[3,7],
                                        ferritin_LOA_F[4,7],
                                        ferritin_LOA_F[5,7],
                                        ferritin_LOA_F[6,7],
                                        ferritin_LOA_F[7,7],
                                        ferritin_LOA_F[8,7],
                                        ferritin_LOA_F[9,7],
                                        ferritin_LOA_F[10,7],
                                        ferritin_LOA_F[11,7],
                                        ferritin_LOA_F[12,7]
                                )) |> 
  mutate(lower=as.numeric(lower),
         study=fct_relevel(study,rev(c("Adult Females: Model 2",
                                       "Leave One Out Analysis",
                                       "Diabetes = Yes",
                                       "Hypertension = Yes",
                                       "CKD = Yes",
                                       "Smokers",
                                       "CRP>1 mg/dL",
                                       "CRP>3 mg/dL",
                                       "BMI>25",
                                       "Adults (18-65 years)",
                                       "Older Adults (>=65 years)",
                                       "LDL >100 mg/dL",
                                       "HDL <50 mg/dL",
                                       "TAG >150 mg/dL"))))

loa_labels <- rev(c("**Adult Females: Model 2**",
                    "***Leave One Out Analysis***",
                    "Diabetes = Yes",
                    "Hypertension = Yes",
                    "CKD = Yes",
                    "Smokers",
                    "CRP>1 mg/dL",
                    "CRP>3 mg/dL",
                    "BMI>25",
                    "Adults (18-65 years)",
                    "Older Adults (>=65 years)",
                    "LDL >100 mg/dL",
                    "HDL <50 mg/dL",
                    "TAG >150 mg/dL"))

#plot
#create forest plot

ferritin_LOA_F.f1 <- df_ferritin_LOA_F |>
  ggplot(aes(y = study, x = effect, xmin = lower, xmax = upper)) +
  ggpck_for.h1() +
  coord_cartesian(xlim = c(-0.05, 0.1), ylim=c(-2,15), clip = "off") +  # Adjusted x-axis limit
  geom_point(aes(color = p.value < 0.05), size = 3) +
  geom_text(label = df_ferritin_LOA_F$label, x = 0.075, color = "black") +  # Adjusted x position
  geom_text(label = "Estimate (95% CI), P.Value", x = 0.075, y = 14.75, color = "#525252",fontface="bold") +
  geom_text(label = "Decreased IMT", x = -0.03, y = -1.5, color = "#525252") +  # Adjusted x position
  geom_text(label = "Increased IMT", x = 0.03, y = -1.5, color = "#525252") +  # Adjusted x position
  labs(title = 'Leave One Out Analysis: Ferritin and IMT (Females)', x = '', y = '') 

ferritin_LOA_F.f1 |> ggsave(filename=here::here("graphs","ferritin_LOA_F.png"),
                            width=12.5,height=8,dpi=300)
beepr::beep()
```
